In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download("popular")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import re
import string
import gensim

C:\Users\ajmer\AppData\Roaming\Python\Python39\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\ajmer\AppData\Roaming\Python\Python39\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\ajmer\AppData\Roaming\Python\Python39\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to
[nltk_data]    |     C:\Users\ajmer\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to
[nltk_data]    |     C:\Users\ajmer\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to
[nltk_data]    |     C:\Users\ajmer\AppData\Roaming\nltk_data...
[nltk_data]    | 

In [2]:
df = pd.read_csv(r"C:\Users\ajmer\NLP\train (2).csv")
df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [3]:
def preprocess(sentences):
  tweet_list = []
  filter = string.ascii_letters + " "
  lm = WordNetLemmatizer()
  for tweet in sentences:
    tweet_cleaned = re.sub(r'http\S+', '', tweet)
    tweet_cleaned = "".join([chr for chr in tweet_cleaned if chr in filter])
    tweet_cleaned = tweet_cleaned.lower()
    tokens = word_tokenize(tweet_cleaned)
    clean_list = [word for word in tokens if word not in stopwords.words('english')]
    clean_list = [lm.lemmatize(word) for word in clean_list]
    tweet_cleaned = " ".join(clean_list)
    tweet_list.append(tweet_cleaned)

  return np.array(tweet_list)

In [4]:
df['text']=preprocess(df["text"])

In [5]:
df.head()

id keyword location                                               text  \
0   1     NaN      NaN         deed reason earthquake may allah forgive u   
1   4     NaN      NaN              forest fire near la ronge sask canada   
2   5     NaN      NaN  resident asked shelter place notified officer ...   
3   6     NaN      NaN  people receive wildfire evacuation order calif...   
4   7     NaN      NaN  got sent photo ruby alaska smoke wildfire pour...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [6]:
# drop duplicates
df["text"].duplicated().sum()
df.drop_duplicates(subset=["text"],inplace=True)

In [7]:
df["text"].duplicated().sum()

0

In [8]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["target"]

# Use train_test_split to split training data into training and validation sets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)


In [9]:
# Check the lengths
len(X_train), len(y_train), len(X_valid), len(y_valid)

(5479, 5479, 1370, 1370)

In [10]:
X_train.head()

4297                              hellfireev jackperu one
4422    ransomware hold bc man computer file hostage v...
4283    day without phone due slow shite computer utte...
275     rt janenelson rt stephenscifi adaptation watch...
876     rolandonabeats ellie goulding blood acesse nos...
Name: text, dtype: object

In [11]:
# Number of unique words in X_train
vocab = []
for tweet in X_train:
    vocab.extend(tweet.split())
len(set(vocab))

13578

In [12]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

# Create a TextVectorization layer
text_vectorizer = TextVectorization(max_tokens=None, 
                                    standardize="lower_and_strip_punctuation", 
                                    split="whitespace", 
                                    ngrams=None, 
                                    output_mode="int", 
                                    output_sequence_length=None)

In [13]:
text_vectorizer.adapt(X_train)

In [15]:
import random
random.choice(range(len(X_train)))

1515

In [17]:
import random
random_index=random.choice(range(len(X_train)))
tweet=X_train.iloc[random_index]
print(tweet)
text_vectorizer(tweet)

listening blower tuffers aussie batting collapse trent bridge reminds love bbctms wonderful stuff engvaus


<tf.Tensor: shape=(14,), dtype=int64, numpy=
array([ 1362, 12707,  5486,  2370,  4636,    78,  1173,   278,  1498,
          34, 12920,  1931,   972, 11075], dtype=int64)>

In [18]:
text_vectorizer("hjgfhjdg djshflihlkjdsaf")

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1], dtype=int64)>

In [19]:
word_in_vocab=text_vectorizer.get_vocabulary()
len(word_in_vocab)

13580

In [21]:
word_in_vocab[-200:]

['alexhammerstone',
 'alexeivolkov',
 'alexandrapullin',
 'alekalicante',
 'aleisstokes',
 'alec',
 'aldridge',
 'alcoholismaddiction',
 'alcoholandmetal',
 'albertsons',
 'albertans',
 'albeit',
 'albany',
 'alba',
 'alaskan',
 'alarmingly',
 'alarming',
 'alarmems',
 'alamodc',
 'alabamaquake',
 'ala',
 'akxbskdn',
 'akx',
 'akwa',
 'akumareisu',
 'akrams',
 'akito',
 'akilah',
 'akgovbillwalker',
 'akame',
 'ajw',
 'ajabrown',
 'aitchkaycee',
 'aisumage',
 'aisle',
 'airwave',
 'airstrikes',
 'airlift',
 'airing',
 'airi',
 'airhorns',
 'airhead',
 'airbullet',
 'airasia',
 'aintsheperty',
 'aimlessly',
 'aiii',
 'aiginsurance',
 'aidan',
 'aias',
 'ahuh',
 'ahrar',
 'ahmazing',
 'ahhtheenikki',
 'ahhhhh',
 'ahhhh',
 'ahahahga',
 'agusa',
 'aguero',
 'agtparis',
 'agthanover',
 'agrees',
 'agreement',
 'agochicago',
 'agnus',
 'aggressively',
 'aggressif',
 'aggarwal',
 'ageekyfangirl',
 'agdq',
 'agalloch',
 'afycso',
 'aftershockorg',
 'aftershockdelo',
 'afterhours',
 'afterhaiya